### ISSUE TITLE
Does license need to align with other CfA projects?

### ISSUE THREAD

**Issue by anselmbradford** [codeforamerica/OpenReferral#34]
Other projects under the CfA org have a CfA-tailored license (e.g. https://github.com/codeforamerica/ohana-web-search/blob/master/LICENSE.md). Should this project have that also?

**Comment by spara** [comment]
License is public domain

**Comment by greggish** [comment]
The README says that "This work is licensed under the Creative Commons Attribution 3.0 Unported License." I think that if this was going to change, it should be discussed -- and I think a case can be made that changing to ShareAlike is more appropriate than changing to Public Domain.

**Comment by webmaven** [comment]
For that matter, licensing or releasing something as 'public domain' (if you aren't actually a government like the USG) can be rather difficult and nebulous depending on the legal regimes of the user and the author, and a simple statement won't do. The license closest to accomplishing the effect of a generic PD status for a copyrighted work that I've seen is the CC0 license: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by spara** [comment]
The spec is the work of a group of people that freely worked towards the greater good of data sharing. Constraining with a Creative Commons Attribution 3.0 that was automatically put by a CFA bot on repositories residing in it's github account seems disingenuous as to its origins and its purpose. The spec has had a public domain license from the start, despite what a CfA script automatically added to a repo. I'm OK with a CC0 license because it's closest to the intent of unlimited access and use.

**Comment by greggish** [comment]
Without staking a particular claim on CC 3.0 itself, I think that our interest in the greater good means that the logic here is complicated in a way that I don't think Public Domain (and possibly not CC0) address. 

It's in the greater good to preserve interoperability among the tools and data that emerge from this work; it's also in the greater good to ensure that even as people use this model in new ways, there are safeguards against proprietary capture.

This is going to require some deliberation; in the meantime, we shouldn't lock ourselves into a totally unrestricted position.
